### ISSUE TITLE
don't raise an error if the project don't use mathlib

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#10]
Why is this Action set to error in mathlib-independent repositories?

```yml
    - name: Give up if not using mathlib
      if: steps.check-mathlib.outputs.uses_mathlib == 'false'
      run: |
        echo "This action requires the lean project to have mathlib as a dependency." 
        exit 1
      shell: bash
```
